/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Task } from "./interfaces/interfaces";
export namespace Components {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface InputSection {
    }
    interface ListSection {
        "tasks": Task[];
    }
    interface MainHeader {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLInputSectionElement extends Components.InputSection, HTMLStencilElement {
    }
    var HTMLInputSectionElement: {
        prototype: HTMLInputSectionElement;
        new (): HTMLInputSectionElement;
    };
    interface HTMLListSectionElement extends Components.ListSection, HTMLStencilElement {
    }
    var HTMLListSectionElement: {
        prototype: HTMLListSectionElement;
        new (): HTMLListSectionElement;
    };
    interface HTMLMainHeaderElement extends Components.MainHeader, HTMLStencilElement {
    }
    var HTMLMainHeaderElement: {
        prototype: HTMLMainHeaderElement;
        new (): HTMLMainHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "input-section": HTMLInputSectionElement;
        "list-section": HTMLListSectionElement;
        "main-header": HTMLMainHeaderElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface InputSection {
        "onNewTask"?: (event: CustomEvent<any>) => void;
    }
    interface ListSection {
        "onDeleteTask"?: (event: CustomEvent<any>) => void;
        "tasks"?: Task[];
    }
    interface MainHeader {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-root": AppRoot;
        "input-section": InputSection;
        "list-section": ListSection;
        "main-header": MainHeader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "input-section": LocalJSX.InputSection & JSXBase.HTMLAttributes<HTMLInputSectionElement>;
            "list-section": LocalJSX.ListSection & JSXBase.HTMLAttributes<HTMLListSectionElement>;
            "main-header": LocalJSX.MainHeader & JSXBase.HTMLAttributes<HTMLMainHeaderElement>;
        }
    }
}
